### ISSUE TITLE
Not working anymore, because MVG API changed

### ISSUE THREAD

**Issue by michidk** [FaisalBinAhmed/MVGFahrinfo#16]
The new URL seems to be

`https://www.mvg.de/api/bgw-pt/v3/departures?globalId=${stationId}`

Which can be further supplied with arguments
`https://www.mvg.de/api/bgw-pt/v3/departures?globalId=${stationId}&limit=100&transportTypes=UBAHN,REGIONAL_BUS,BUS,TRAM,SBAHN`

**Comment by FaisalBinAhmed** [comment]
Thanks for posting this, I also noticed this today. Will update soon

**Comment by FaisalBinAhmed** [comment]
@michidk the issue has been fixed now. If you're using the crates.io version, please use v1.2.0
