### ISSUE TITLE
ETA Display Issue

### ISSUE THREAD

**Issue by Luz5020** [FaisalBinAhmed/MVGFahrinfo#3]
Running this on a raspberry Pi and ocassionally the displayed ETA seems to underflow. I've attached a Screenshot, if you need anything else lmk! 
![grafik](https://github.com/FaisalBinAhmed/MVGFahrinfo/assets/43752735/3d3d804c-44dc-4b65-b16b-c6c0087a5afc)

**Comment by FaisalBinAhmed** [comment]
Thanks for opening up the issue. @Luz5020 

I am aware of the problem and added a comment in the source code to address it later. Didn't expect people to actually use the app. :)

I am glad people are running it on a raspberry Pi.

I will try to fix the issue soon. I will keep this open until I fix this.

**Comment by Luz5020** [comment]
I love the display function, I'd like to build a little screen that shows my local stop. Thanks for this 👍

**Comment by FaisalBinAhmed** [comment]
Do post pictures once you build this. I'd love to see that. :)

**Comment by Luz5020** [comment]
I will, currently procuring a Display for this

**Comment by FaisalBinAhmed** [comment]
Hi, I fixed the underflow issue in https://github.com/FaisalBinAhmed/MVGFahrinfo/pull/10. If you're using the crates version, look for version 1.1.0 :) @Luz5020

**Comment by Luz5020** [comment]
Perfect, I'll try it tomorrow

**Comment by rafael747** [comment]
Hey, I used this project as an inspiration for this one: https://github.com/rafael747/i75w-mvg-farhinfo
It uses a RP Pico W to show departure information in a LED Matrix panel
It might be useful if you are planning to have a external display for this purpose
cc. @Luz5020 @FaisalBinAhmed

**Comment by FaisalBinAhmed** [comment]
@rafael747 your project looks great! I'm glad someone got inspired by my little project. 😁
