### ISSUE TITLE
Can not enter the char 'c' in the searchbar

### ISSUE THREAD

**Issue by cato447** [FaisalBinAhmed/MVGFahrinfo#4]
When searching for a station the character c is not accepted as input.

For example:
Searching for Candidplatz results in only the string andidplatz getting displayed in the searchbox <img width="1439" alt="image" src="https://github.com/FaisalBinAhmed/MVGFahrinfo/assets/47259183/8b713c67-c67f-45ca-96fb-ff44765461a4">

For stations like Candidplatz this is not an issue since the station will be found either way.
However this is problematic for stations like Hackerbrücke which result in the search string Hakerbrüke which is obviously not yielding any results.

**Comment by cato447** [comment]
I looked into the Codebase and found why the program is behaving like this

In [update.rs at line 51](https://github.com/FaisalBinAhmed/MVGFahrinfo/blob/fbe55b590576b6b385832c8641c0abeef6fbdd03/src/update.rs#L51) following code matches any 'c' or 'C' entered into the search bar and just ignores it.

```rust
KeyCode::Char('c') | KeyCode::Char('C') => {
    if key_event.modifiers == KeyModifiers::CONTROL {
        app.quit()
    }
}
```

**Comment by FaisalBinAhmed** [comment]
Hey thanks for opening this, looks like I made a blunder when copying over the code from normal mode. I already opened a PR #5 to fix this :)

**Comment by cato447** [comment]
Perfect thanks 👍
