### ISSUE TITLE
Question regarding mvg api

### ISSUE THREAD

**Issue by bq-wrongway** [FaisalBinAhmed/MVGFahrinfo#6]
Hi, not an issue but more of question/ suggestion.

Where did you find mvg api endpoints? I did not manage to find it ob their website, also would is be possible to add a tracker to certain line, for example to see if there are issues with S2 or U2.

**Comment by FaisalBinAhmed** [comment]
There's this `messages` field under `DepartureInfo` struct you can look at. Usually MVG posts line related updates there, if any. I haven't used it in the app yet. 

What you are describing is maybe not available as an API. Perhaps you have to parse it manually from their status website.

There's a python library which documents many of these endpoints; you can look here: https://python-mvg-departures.readthedocs.io/en/latest/
